Switched from using -jar execution to -cp
When using -jar option the JAR file is source of all user classes but
other user class path settings are ignored.

As no class path entries are defined in this jar manifest so must
specify all on command line via this syntax to avoid
java.lang.NoClassDefFoundError errors.